export default [
  { name: "10th Pass", level: "10th", field: null, isEquivalentTo: "10th" },
  { name: "12th Pass (Science)", level: "12th", field: "Science", isEquivalentTo: "12th" },
  { name: "12th Pass (Commerce)", level: "12th", field: "Commerce", isEquivalentTo: "12th" },
  { name: "12th Pass (Arts)", level: "12th", field: "Arts", isEquivalentTo: "12th" },
  { name: "Bachelor of Arts (B.A)", level: "graduate", field: "Arts", isEquivalentTo: "graduate" },
  { name: "Bachelor of Science (B.Sc)", level: "graduate", field: "Science", isEquivalentTo: "graduate" },
  { name: "Bachelor of Commerce (B.Com)", level: "graduate", field: "Commerce", isEquivalentTo: "graduate" },
  { name: "Bachelor of Technology (B.Tech CSE)", level: "engineering", field: "Computer Science and Engineering", isEquivalentTo: "graduate" },
  { name: "Bachelor of Technology (B.Tech EEE)", level: "engineering", field: "Electrical and Electronics Engineering", isEquivalentTo: "graduate" },
  { name: "Bachelor of Technology (B.Tech ME)", level: "engineering", field: "Mechanical Engineering", isEquivalentTo: "graduate" },
  { name: "Bachelor of Technology (B.Tech CE)", level: "engineering", field: "Civil Engineering", isEquivalentTo: "graduate" },
  { name: "Bachelor of Technology (B.Tech ECE)", level: "engineering", field: "Electronics and Communication Engineering", isEquivalentTo: "graduate" },
  { name: "Bachelor of Education (B.Ed)", level: "graduate", field: "Education", isEquivalentTo: "graduate" },
  { name: "Bachelor of Laws (LLB)", level: "graduate", field: "Law", isEquivalentTo: "graduate" },
  { name: "Master of Arts (M.A)", level: "postgraduate", field: "Arts", isEquivalentTo: "postgraduate" },
  { name: "Master of Science (M.Sc)", level: "postgraduate", field: "Science", isEquivalentTo: "postgraduate" },
  { name: "Master of Commerce (M.Com)", level: "postgraduate", field: "Commerce", isEquivalentTo: "postgraduate" },
  { name: "Master of Technology (M.Tech)", level: "postgraduate", field: "Engineering", isEquivalentTo: "postgraduate" },
  { name: "Master of Business Administration (MBA)", level: "postgraduate", field: "Business Administration", isEquivalentTo: "postgraduate" },
  { name: "Doctor of Medicine (MBBS)", level: "medical", field: "Medicine", isEquivalentTo: "postgraduate" },
  { name: "Bachelor of Medicine and Bachelor of Surgery (MBBS)", level: "medical", field: "Medicine", isEquivalentTo: "graduate" },
  { name: "Ph.D", level: "phd", field: null, isEquivalentTo: "phd" },
  { name: "Diploma in Engineering (3-year)", level: "diploma", field: "Engineering", isEquivalentTo: "graduate" },
  { name: "Diploma in Engineering (2-year)", level: "diploma", field: "Engineering", isEquivalentTo: "12th" },
  { name: "Diploma in Education (D.Ed)", level: "diploma", field: "Education", isEquivalentTo: "graduate" },
  { name: "Diploma in Elementary Education (D.El.Ed)", level: "diploma", field: "Education", isEquivalentTo: "graduate" },
  { name: "Diploma in Pharmacy (D.Pharm)", level: "diploma", field: "Pharmacy", isEquivalentTo: "graduate" },
  { name: "Diploma in Management", level: "diploma", field: "Management", isEquivalentTo: "graduate" },
  { name: "Diploma in Computer Applications (DCA)", level: "diploma", field: "Computer Applications", isEquivalentTo: "graduate" }
]
