export default [
  { name: "Andhra Pradesh", code: "AP", region: "south", districts: ["Anantapur", "Chittoor", "East Godavari", "Guntur", "Krishna", "Kurnool", "Nellore", "Prakasam", "Srikakulam", "Visakhapatnam", "Vizianagaram", "West Godavari", "YSR Kadapa"] },
  { name: "Arunachal Pradesh", code: "AR", region: "northeast", districts: ["Tawang", "West Kameng", "East Kameng", "Papum Pare", "Lower Subansiri", "Upper Subansiri", "West Siang", "East Siang", "Upper Siang", "Changlang", "Tirap", "Longding"] },
  { name: "Assam", code: "AS", region: "northeast", districts: ["Tinsukia", "Dibrugarh", "Sivasagar", "Jorhat", "Golaghat", "Karbi Anglong", "Nagaon", "Morigaon", "Dhemaji", "Lakhimpur", "Sonitpur", "Darrang", "Kamrup", "Nalbari", "Barpeta"] },
  { name: "Bihar", code: "BR", region: "east", districts: ["Patna", "Gaya", "Nalanda", "Vaishali", "Bhagalpur", "Muzaffarpur", "Darbhanga", "Aurangabad", "Rajgir", "Buxar", "Bhojpur", "Siwan", "Saran", "Purnia", "Katihar"] },
  { name: "Chhattisgarh", code: "CG", region: "central", districts: ["Raipur", "Bhilai", "Bilaspur", "Durg", "Korba", "Jagdalpur", "Ambikapur", "Rajnandgaon", "Dhamtari", "Kabirdham", "Janjgir-Champa"] },
  { name: "Goa", code: "GA", region: "west", districts: ["North Goa", "South Goa"] },
  { name: "Gujarat", code: "GJ", region: "west", districts: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Jamnagar", "Bhuj", "Gandhinagar", "Junagadh", "Bharuch", "Anand", "Mehsana", "Patan"] },
  { name: "Haryana", code: "HR", region: "north", districts: ["Gurugram", "Faridabad", "Panipat", "Karnal", "Hisar", "Ambala", "Rohtak", "Jind", "Bhiwani", "Sonipat", "Palwal", "Yamunanagar"] },
  { name: "Himachal Pradesh", code: "HP", region: "north", districts: ["Shimla", "Kullu", "Manali", "Dharamsala", "Mandi", "Hamirpur", "Bilaspur", "Chamba", "Kangra", "Solan", "Una", "Sirmaur"] },
  { name: "Jharkhand", code: "JH", region: "east", districts: ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Hazaribagh", "Deoghar", "Giridih", "Dumka", "Godda", "Sahebganj", "Palamu"] },
  { name: "Karnataka", code: "KA", region: "south", districts: ["Bengaluru Urban", "Mysuru", "Mangaluru", "Hubballi-Dharwad", "Belagavi", "Kalaburagi", "Ballari", "Davangere", "Shimoga", "Tumakuru", "Hassan", "Raichur"] },
  { name: "Kerala", code: "KL", region: "south", districts: ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam", "Alappuzha", "Palakkad", "Malappuram", "Kannur", "Wayanad", "Idukki", "Kasargod"] },
  { name: "Madhya Pradesh", code: "MP", region: "central", districts: ["Bhopal", "Indore", "Gwalior", "Jabalpur", "Ujjain", "Sagar", "Satna", "Rewa", "Katni", "Chhindwara", "Balaghat", "Vidisha"] },
  { name: "Maharashtra", code: "MH", region: "west", districts: ["Mumbai", "Pune", "Nagpur", "Thane", "Nashik", "Aurangabad", "Solapur", "Kolhapur", "Amravati", "Jalgaon", "Ahmednagar", "Satara"] },
  { name: "Manipur", code: "MN", region: "northeast", districts: ["Imphal West", "Imphal East", "Thoubal", "Bishnupur", "Churachandpur", "Ukhrul", "Senapati", "Tamenglong", "Chandel"] },
  { name: "Meghalaya", code: "ML", region: "northeast", districts: ["East Khasi Hills", "West Khasi Hills", "South West Khasi Hills", "East Jaintia Hills", "West Jaintia Hills", "East Garo Hills", "West Garo Hills", "South Garo Hills", "North Garo Hills"] },
  { name: "Mizoram", code: "MZ", region: "northeast", districts: ["Aizawl", "Lunglei", "Champhai", "Kolasib", "Serchhip", "Mamit", "Saiha"] },
  { name: "Nagaland", code: "NL", region: "northeast", districts: ["Kohima", "Dimapur", "Mokokchung", "Tuensang", "Mon", "Phek", "Wokha", "Zunheboto"] },
  { name: "Odisha", code: "OR", region: "east", districts: ["Bhubaneswar", "Cuttack", "Puri", "Sambalpur", "Berhampur", "Balasore", "Mayurbhanj", "Keonjhar", "Sundargarh", "Jajpur", "Khordha"] },
  { name: "Punjab", code: "PB", region: "north", districts: ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Mohali", "Pathankot", "Moga", "Sangrur", "Hoshiarpur", "Kapurthala"] },
  { name: "Rajasthan", code: "RJ", region: "west", districts: ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Ajmer", "Alwar", "Bikaner", "Bharatpur", "Pali", "Sikar", "Tonk", "Chittorgarh"] },
  { name: "Sikkim", code: "SK", region: "northeast", districts: ["East Sikkim", "West Sikkim", "North Sikkim", "South Sikkim"] },
  { name: "Tamil Nadu", code: "TN", region: "south", districts: ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tirunelveli", "Erode", "Vellore", "Thoothukudi", "Dindigul", "Krishnagiri", "Tiruvannamalai"] },
  { name: "Telangana", code: "TS", region: "south", districts: ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Khammam", "Nalgonda", "Mahbubnagar", "Rangareddy", "Siddipet", "Mancherial"] },
  { name: "Tripura", code: "TR", region: "northeast", districts: ["West Tripura", "North Tripura", "South Tripura", "Dhalai", "Sepahijala", "Gomati", "Unakoti", "Khowai"] },
  { name: "Uttar Pradesh", code: "UP", region: "north", districts: ["Lucknow", "Noida", "Varanasi", "Agra", "Prayagraj", "Kanpur", "Meerut", "Ghaziabad", "Bareilly", "Aligarh", "Jhansi", "Gorakhpur", "Agra"] },
  { name: "Uttarakhand", code: "UK", region: "north", districts: ["Dehradun", "Haridwar", "Haldwani", "Roorkee", "Rishikesh", "Nainital", "Almora", "Chamoli", "Pithoragarh", "Uttarkashi"] },
  { name: "West Bengal", code: "WB", region: "east", districts: ["Kolkata", "Howrah", "Darjeeling", "Siliguri", "Asansol", "Durgapur", "Bardhaman", "Murshidabad", "Nadia", "24 Parganas North", "24 Parganas South"] },

  // Union Territories
  { name: "Andaman and Nicobar Islands", code: "AN", region: "islands", districts: ["South Andaman", "North and Middle Andaman", "Nicobar"] },
  { name: "Chandigarh", code: "CH", region: "north", districts: ["Chandigarh"] },
  { name: "Dadra and Nagar Haveli and Daman and Diu", code: "DD", region: "west", districts: ["Dadra and Nagar Haveli", "Daman", "Diu"] },
  { name: "Delhi", code: "DL", region: "north", districts: ["New Delhi", "Central Delhi", "North Delhi", "South Delhi", "East Delhi", "West Delhi", "Shahdara", "North East Delhi", "North West Delhi", "South East Delhi", "South West Delhi"] },
  { name: "Jammu and Kashmir", code: "JK", region: "north", districts: ["Srinagar", "Jammu", "Anantnag", "Budgam", "Baramulla", "Kupwara", "Pulwama", "Udhampur", "Kathua", "Rajouri", "Poonch"] },
  { name: "Ladakh", code: "LA", region: "north", districts: ["Leh", "Kargil"] },
  { name: "Lakshadweep", code: "LD", region: "islands", districts: [""] },
  { name: "Puducherry", code: "PY", region: "south", districts: ["Puducherry", "Karaikal", "Mahe", "Yanam"] }
]
