export default [
  {
    topicName: "Analogies",
    title: "UPSC EPFO APFC 2026: Social Security PYQs Revision",
    youtubeVideoId: "_As8gDXKSUI",
    youtubeUrl: "https://www.youtube.com/watch?v=_As8gDXKSUI",
    channelName: "Drishti IAS English",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Ancient India",
    title: "Complete Ancient Indian History",
    youtubeVideoId: "2q8J0oA-ra8",
    youtubeUrl: "https://www.youtube.com/watch?v=2q8J0oA-ra8",
    channelName: "Lecture 1 Pre Historic India",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Awards & Honours",
    title: "Major Awards",
    youtubeVideoId: "RIIqmsSfi50",
    youtubeUrl: "https://www.youtube.com/watch?v=RIIqmsSfi50",
    channelName: "UPSC Prelims 2025",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Banking & Finance",
    title: "Complete Banking in India in one SHOT for All Competitive Exams",
    youtubeVideoId: "yDr-M4rfLXI",
    youtubeUrl: "https://www.youtube.com/watch?v=yDr-M4rfLXI",
    channelName: "UPSC 2026 Prelims",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Biology",
    title: "How to prepare General Science for UPSC CSE \u0026 State PSCs ? Introduction to Biology by Dr Ravisir",
    youtubeVideoId: "iMsji5ufdjs",
    youtubeUrl: "https://www.youtube.com/watch?v=iMsji5ufdjs",
    channelName: "StudyIQ IAS",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Blood Relations",
    title: "Blood Relations",
    youtubeVideoId: "u6qI3Wpe2_o",
    youtubeUrl: "https://www.youtube.com/watch?v=u6qI3Wpe2_o",
    channelName: "Crack UPSC CSE/IAS 2021",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Books & Authors",
    title: "Complete UPSC Syllabus Explained for Beginners",
    youtubeVideoId: "EzfjB0wMJQw",
    youtubeUrl: "https://www.youtube.com/watch?v=EzfjB0wMJQw",
    channelName: "Drishti IAS English",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Budget & Fiscal Policy",
    title: "Types of Budget",
    youtubeVideoId: "WWhR20QuqYA",
    youtubeUrl: "https://www.youtube.com/watch?v=WWhR20QuqYA",
    channelName: "Economy lecture by Himanshu Dhingra",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Chemistry",
    title: "National Programmes On Advanced Chemistry Cell Battery Storage-Govt. Schemes",
    youtubeVideoId: "qn6drfS3sao",
    youtubeUrl: "https://www.youtube.com/watch?v=qn6drfS3sao",
    channelName: "Chemistry General Science Indian Air Force Indian competitive exam English Study",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Climatology",
    title: "Climate",
    youtubeVideoId: "MUvTrPMNEgY",
    youtubeUrl: "https://www.youtube.com/watch?v=MUvTrPMNEgY",
    channelName: "Lecture 4 - NCERT Free Series",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Cloze Test",
    title: "Bank Exam 2026",
    youtubeVideoId: "jxtai6GeasU",
    youtubeUrl: "https://www.youtube.com/watch?v=jxtai6GeasU",
    channelName: "English for Bank Exams",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Coding-Decoding",
    title: "UPSC CSAT - Coding Decoding",
    youtubeVideoId: "7mRQrlYT03I",
    youtubeUrl: "https://www.youtube.com/watch?v=7mRQrlYT03I",
    channelName: "Complete CSAT Free Series",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Computer Hardware",
    title: "NTA UGC NET:JRF",
    youtubeVideoId: "6FbpFS0gi_o",
    youtubeUrl: "https://www.youtube.com/watch?v=6FbpFS0gi_o",
    channelName: "Paper I",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Current Affairs",
    title: "The Hindu Newspaper Analysis",
    youtubeVideoId: "8tnlNPNuSQo",
    youtubeUrl: "https://www.youtube.com/watch?v=8tnlNPNuSQo",
    channelName: "UPSC, PIB \u0026 Editorial Current Affairs Today",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Cyber Security",
    title: "MindMaps for UPSC - Cyber security (Science \u0026 Technology/Internal Security)",
    youtubeVideoId: "NmbcQ0dSdUw",
    youtubeUrl: "https://www.youtube.com/watch?v=NmbcQ0dSdUw",
    channelName: "Drishti IAS : English",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Data Interpretation",
    title: "The Hindu Newspaper Analysis",
    youtubeVideoId: "xwD3mx1Jwmo",
    youtubeUrl: "https://www.youtube.com/watch?v=xwD3mx1Jwmo",
    channelName: "UPSC, PIB \u0026 Editorial Current Affairs Today",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Economic Geography",
    title: "Complete World Mapping",
    youtubeVideoId: "aIEzgv9bOtw",
    youtubeUrl: "https://www.youtube.com/watch?v=aIEzgv9bOtw",
    channelName: "Continent Series",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Environment",
    title: "UPSC Prelims PYQ Analysis (2019-2024)",
    youtubeVideoId: "-Z8P2ej68es",
    youtubeUrl: "https://www.youtube.com/watch?v=-Z8P2ej68es",
    channelName: "Part-I",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Error Spotting",
    title: "Error Spotting detection correction for Competitive Exams SSC CGL 2015",
    youtubeVideoId: "SWnzo2tyHrs",
    youtubeUrl: "https://www.youtube.com/watch?v=SWnzo2tyHrs",
    channelName: "StudyIQ IAS",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Essay Writing",
    title: "Essay Detailed Discussion",
    youtubeVideoId: "CJlv3G_hpf0",
    youtubeUrl: "https://www.youtube.com/watch?v=CJlv3G_hpf0",
    channelName: "Essay Writing UPSC",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Fundamental Rights",
    title: "Complete Fundamental Rights",
    youtubeVideoId: "k7cP27jdScs",
    youtubeUrl: "https://www.youtube.com/watch?v=k7cP27jdScs",
    channelName: "Shashank Tyagi",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Hindi Grammar",
    title: "What Is Merchant Discount Rate (MDR)?",
    youtubeVideoId: "Oeib45PTDFo",
    youtubeUrl: "https://www.youtube.com/watch?v=Oeib45PTDFo",
    channelName: "UPSC",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Hindi Vocabulary",
    title: "Learn Vocabulary English Words in HINDI - IBPS PO + Clerk , SSC CGL + CHSL",
    youtubeVideoId: "rsQoGQG1dbc",
    youtubeUrl: "https://www.youtube.com/watch?v=rsQoGQG1dbc",
    channelName: "StudyIQ IAS",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Indian Constitution",
    title: "Complete Indian Polity for UPSC CSE 2025-26",
    youtubeVideoId: "rSZ69uc6qjw",
    youtubeUrl: "https://www.youtube.com/watch?v=rSZ69uc6qjw",
    channelName: "Introduction in English by Shashank Tyagi",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Indian Economy Basics",
    title: "Complete Indian Economy in One Shot",
    youtubeVideoId: "BMORCGp_83A",
    youtubeUrl: "https://www.youtube.com/watch?v=BMORCGp_83A",
    channelName: "UPSC NCERT 🎯",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Indian Geography",
    title: "India - Location",
    youtubeVideoId: "GDPsyhSLq94",
    youtubeUrl: "https://www.youtube.com/watch?v=GDPsyhSLq94",
    channelName: "Lecture 1 - NCERT Free Series",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Indian National Movement",
    title: "History's Highest Yield Topics",
    youtubeVideoId: "HbKU5GVGoyA",
    youtubeUrl: "https://www.youtube.com/watch?v=HbKU5GVGoyA",
    channelName: "UPSC Beginners \u0026 Mains",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "International Economics",
    title: "UPSC 2027 Economics Marathon: Complete Indian Economy in One Go",
    youtubeVideoId: "9XKPtNccJXM",
    youtubeUrl: "https://www.youtube.com/watch?v=9XKPtNccJXM",
    channelName: "International Economics Economics State PSC Indian competitive exam English Stud",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Internet & Networking",
    title: "NTA UGC NET:JRF",
    youtubeVideoId: "sw04tlhhB-I",
    youtubeUrl: "https://www.youtube.com/watch?v=sw04tlhhB-I",
    channelName: "Paper I",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Judiciary",
    title: "Judiciary",
    youtubeVideoId: "f7rYy5DMBio",
    youtubeUrl: "https://www.youtube.com/watch?v=f7rYy5DMBio",
    channelName: "Lecture 8 - NCERT Free Series",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Mean, Median, Mode",
    title: "Mean, Median and Mode",
    youtubeVideoId: "lKv98-jkfIE",
    youtubeUrl: "https://www.youtube.com/watch?v=lKv98-jkfIE",
    channelName: "Govt Exams",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Medieval India",
    title: "Complete Medieval History in One Shot",
    youtubeVideoId: "FH9GVCoVEPM",
    youtubeUrl: "https://www.youtube.com/watch?v=FH9GVCoVEPM",
    channelName: "UPSC Prelims 2026 🎯",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Modern India",
    title: "Complete Modern History for UPSC 2027",
    youtubeVideoId: "Btu6Y1Q9lFA",
    youtubeUrl: "https://www.youtube.com/watch?v=Btu6Y1Q9lFA",
    channelName: "By Alok Ojha",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Panchayati Raj",
    title: "Complete Indian Polity for UPSC CSE 2025-26",
    youtubeVideoId: "28LPveQRNWs",
    youtubeUrl: "https://www.youtube.com/watch?v=28LPveQRNWs",
    channelName: "StudyIQ",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Parliament",
    title: "Complete Parliament of India",
    youtubeVideoId: "zrkHeeQHkSQ",
    youtubeUrl: "https://www.youtube.com/watch?v=zrkHeeQHkSQ",
    channelName: "Shashank Tyagi",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Percentage",
    title: "CSAT - Percentages",
    youtubeVideoId: "t5LzI2pLgtw",
    youtubeUrl: "https://www.youtube.com/watch?v=t5LzI2pLgtw",
    channelName: "CSAT Simplified",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Physics",
    title: "Complete Science and Tech Revision for UPSC Prelims 2025",
    youtubeVideoId: "IerItfB2vHA",
    youtubeUrl: "https://www.youtube.com/watch?v=IerItfB2vHA",
    channelName: "Physics General Science Indian Air Force Indian competitive exam English StudyIQ",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Poverty & Unemployment",
    title: "Poverty, Inequality \u0026 Unemployment Full Chapter",
    youtubeVideoId: "eAOPE1DMgtE",
    youtubeUrl: "https://www.youtube.com/watch?v=eAOPE1DMgtE",
    channelName: "UPSC Preparation",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Precis Writing",
    title: "Essay Writing Part-6 - All You need to know about Precis Writing",
    youtubeVideoId: "VXrGczqzkxQ",
    youtubeUrl: "https://www.youtube.com/watch?v=VXrGczqzkxQ",
    channelName: "StudyIQ IAS",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Probability",
    title: "CSAT - Probability",
    youtubeVideoId: "6xciVD6IZ3Q",
    youtubeUrl: "https://www.youtube.com/watch?v=6xciVD6IZ3Q",
    channelName: "UPSC Prelims 2023",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Profit & Loss",
    title: "CSAT Maths",
    youtubeVideoId: "I0BtqZ208_Q",
    youtubeUrl: "https://www.youtube.com/watch?v=I0BtqZ208_Q",
    channelName: "UPSC Prelims",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Ratio & Proportion",
    title: "Ratio And Proportion",
    youtubeVideoId: "h5ckvGg54NE",
    youtubeUrl: "https://www.youtube.com/watch?v=h5ckvGg54NE",
    channelName: "Crack UPSC CSE/IAS English 2020",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Reading Comprehension",
    title: "UPSC Prelims 2026 GS 2",
    youtubeVideoId: "kivvH2DLXII",
    youtubeUrl: "https://www.youtube.com/watch?v=kivvH2DLXII",
    channelName: "UPSC CSAT 2026",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Seating Arrangements",
    title: "Venn Diagrams \u0026 Seating Arrangements",
    youtubeVideoId: "zyVytYLoPtQ",
    youtubeUrl: "https://www.youtube.com/watch?v=zyVytYLoPtQ",
    channelName: "Neetu Goel",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Sentence Correction",
    title: "Verbs को पढ़िए और समझिये  - Sentence correction + Error spotting + Error finding - SSC CGL \u0026 Bank PO",
    youtubeVideoId: "ztLrd1b9lvY",
    youtubeUrl: "https://www.youtube.com/watch?v=ztLrd1b9lvY",
    channelName: "StudyIQ IAS",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Simple & Compound Interest",
    title: "Simple Interest And Compound Interest",
    youtubeVideoId: "algMI2yN5K4",
    youtubeUrl: "https://www.youtube.com/watch?v=algMI2yN5K4",
    channelName: "Crack UPSC CSE/IAS English 2020",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Space & Technology",
    title: "ISRO: India’s Pride in Space",
    youtubeVideoId: "-yBoeycdnRA",
    youtubeUrl: "https://www.youtube.com/watch?v=-yBoeycdnRA",
    channelName: "UPSC 2026",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Sports",
    title: "Major Sports Events",
    youtubeVideoId: "lkp67LuBUNQ",
    youtubeUrl: "https://www.youtube.com/watch?v=lkp67LuBUNQ",
    channelName: "UPSC Prelims 2025",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Standard Deviation",
    title: "How to Prepare for UPSC?",
    youtubeVideoId: "qVKtL5rWNxU",
    youtubeUrl: "https://www.youtube.com/watch?v=qVKtL5rWNxU",
    channelName: "UPSC 2027",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Static GK",
    title: "The Hindu Analysis \u0026 PIB",
    youtubeVideoId: "-95YvclTFCY",
    youtubeUrl: "https://www.youtube.com/watch?v=-95YvclTFCY",
    channelName: "Current Affairs",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Syllogisms",
    title: "Syllogism (Reasoning) आसान तरीके से सीखे with Tricks \u0026 Shortcuts",
    youtubeVideoId: "2sJtkw7iGGo",
    youtubeUrl: "https://www.youtube.com/watch?v=2sJtkw7iGGo",
    channelName: "OnlyIAS",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "Time & Work",
    title: "Complete Time \u0026 Work Marathon",
    youtubeVideoId: "K3pNN-kylcc",
    youtubeUrl: "https://www.youtube.com/watch?v=K3pNN-kylcc",
    channelName: "StudyIQ IAS",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "World Geography",
    title: "Complete World Mapping",
    youtubeVideoId: "5XCXkkZz1ro",
    youtubeUrl: "https://www.youtube.com/watch?v=5XCXkkZz1ro",
    channelName: "Continent Series",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
  {
    topicName: "World History",
    title: "Complete World History in 8 Hours Through Animation",
    youtubeVideoId: "UiXuBmBaNeA",
    youtubeUrl: "https://www.youtube.com/watch?v=UiXuBmBaNeA",
    channelName: "World History History State PSC Indian competitive exam English StudyIQ IAS Engl",
    language: "english",
    quality: "beginner",
    isVerified: true,
  },
];
